# Generated by Django 3.0.1 on 2020-03-17 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
